### ISSUE TITLE
litespeed admin area

### ISSUE THREAD

**Issue by alireza2281** [techwithus/Linux-OpenLiteSpeed-MySQL-PHP-Server-Docker-Compose#2]
Hello i tried to expose litespeed admin area port 7080 but i could not access the admin area. my question is, what should i do to access admin area?

**Comment by sashuu69** [comment]
Hello @alireza2281 
Did you try:-
- "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
- "${HOST_MACHINE_SECURE_HOST_PORT}:443"
- 7080:7080

I have not tried it yet. I just saw the comment. Please let me know if the issue is fixed. If not, I will try from my side and inform you.

Regards
Sashwat K

**Comment by alireza2281** [comment]
Hello @sashuu6
thanks for your reply, i can't remember what i did to solve the problem but the problem solved thangs for you advise again
